[package]
name = "micro-ecc-sys"
description = "Low-level bindings to micro-ecc"
version = "0.1.2"
authors = ["Nicolas Stalder <n@stalder.io>"]
edition = "2018"
license = "BSD-2-Clause"
readme = "README.md"
categories = ["embedded", "ecc", "cryptography", "no-std"]
repository = "https://github.com/nickray/micro-ecc-sys"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cty = "0.2.1"

[build-dependencies]
bindgen = "0.52.0"
cc = "1.0.25"
